name: Downstream

on:
  push:
    branches:
      - trunk

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger IC Dependency Check
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: acapi_update
          repo: ideacrew/ic_dependency_jamboree
          token: ${{ secrets.GH_PAT }}
          client-payload: '{"ref": "trunk"}'
        


