name: Downstream

on:
  workflow_dispatch:
    branches:
      - trunk
  push:
    branches:
      - trunk

jobs:
  check-dependencies:
    uses: ideacrew/ic_dependency_jamboree/.github/workflows/test_bundle.yml@trunk
    secrets:
      token: ${{ secrets.GH_PAT }}
        


