name: Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.3
      run: |
        sudo add-apt-repository -y ppa:brightbox/ruby-ng
        sudo apt-get -y update
        sudo apt-get -y install ruby2.3 ruby2.3-dev ruby-switch
        sudo apt-get -y install ruby-switch
        sudo ruby-switch --list
        sudo ruby-switch --set ruby2.3
    - name: Cache Gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-openhbx_cv2-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-openhbx_cv2-${{ hashFiles('**/Gemfile.lock') }}
    - name: Install Gems
      run: |
        sudo gem install bundler -v '1.17.3'
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run RSpec
      run: |
        bundle exec rspec
